### ISSUE TITLE
jitter when animating

### ISSUE THREAD

**Issue by j2l** [doakey3/GreaseWriter#2] opened 2019-02-19 11:00 UTC
Thanks for this great addon.
I have an issue at replay thought on Blender 2.8beta 2019-02-15, Win10, XP-Pen G640 tablet:
![image](https://user-images.githubusercontent.com/65325/53008997-ce930580-343a-11e9-809b-9659c6513c7a.png)
![image](https://user-images.githubusercontent.com/65325/53009032-e4082f80-343a-11e9-970b-f19697ff3e76.png)
Any idea?
Do you have other settings?

**Comment by doakey3** [comment] 2019-02-20 01:13
I'm not sure what's going on here. I can't seem to replicate it. Maybe you can give me a sample .blend file and I can try to figure it out. 

As an alternative, you can add a build modifier to your grease pencil object to achieve a similar effect.

![build](https://user-images.githubusercontent.com/16495887/53058850-58ae8e80-347a-11e9-8290-98c5c8197cfa.jpg)

**Comment by j2l** [comment] 2019-02-20 11:34
Sure, here's a circle drawn with my tablet.
[reanimate.zip](https://github.com/doakey3/GreaseWriter/files/2884423/reanimate.zip)
and my result at frame 45:
![image](https://user-images.githubusercontent.com/65325/53089079-d8386e00-350b-11e9-9c66-8bdee305e1c2.png)


Build modifier works fine, but I can't apply it (no error in console, just plain dead apply button). 
You can try build modifier at frame 46 (it removes reanimate from 0 to 46).

**Comment by doakey3** [comment] 2019-02-21 13:29
I've found that if you draw from the top-down view (press the 7 key on the number pad), then click re-animate, you get the desired result. I think the issue is I may have done some 3D math wrong. I'll take a closer look at it this weekend if I have time.

**Comment by j2l** [comment] 2019-02-22 13:10
Thanks!

**Comment by doakey3** [comment] 2019-02-23 01:52
Fixed with version [0.0.4](https://github.com/doakey3/GreaseWriter/releases/tag/0.0.4)

**Closed as completed by doakey3** 2019-02-23 01:52 UTC
